fixes required for VS2022 compile
perfect-loader\include\pl/hook.hpp(36): error C4596: '{ctor}': illegal qualified name in member declaration
perfect-loader\include\pl/hook.hpp(118): error C3254: 'Pl::HbpHook': class contains explicit override '{ctor}' but does not derive from an interface that contains the function declaration
perfect-loader\include\pl/hook.hpp(118): error C3241: 'Pl::HbpHook::HbpHook(std::byte *,std::byte *,bool)': this method was not introduced by 'Pl::HookBase'
perfect-loader\include\pl/hook.hpp(118): note: see declaration of 'Pl::HbpHook::HbpHook'